name: pipeline

on: 
  workflow_dispatch:

jobs:
  # 1. Get Configuration (External Template)
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml

  # 2. Register Training Environment (Local)
  register-environment:
      needs: get-config
      uses: ./.github/workflows/custom-register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}      
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
  # 3. Register Dataset (Local)
  register-dataset:
    needs: get-config
    uses: ./.github/workflows/custom-register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: teleco-churn-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
      
  # 4. Create Compute (Local)
  create-compute:
      needs: [get-config,register-environment,register-dataset]
      uses: ./.github/workflows/custom-create-compute.yml
      with:
        cluster_name: cpu-cluster
        size: Standard_DS11_v2
        min_instances: 0
        max_instances: 1
        cluster_tier: dedicated
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}      
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
  # 5. Run Training Pipeline (Local)
  run-pipeline:
      needs: [get-config,register-environment,create-compute,register-dataset]
      uses: ./.github/workflows/custom-run-pipeline.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}      
        parameters-file:  mlops/azureml/train/pipeline.yml
        job-name: test
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}

  # 6. Register Deployment Environment (Local)
  register-environment-deploy:
    needs: get-config
    uses: ./.github/workflows/custom-register-environment.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}           
      environment_file:  mlops/azureml/deploy/online/deploy-env.yml
      conda_file: data-science/environment/deploy-conda.yml
    secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
          
  # 7. Create Endpoint (Local)
  create-endpoint:
      needs: [get-config,run-pipeline]
      uses: ./.github/workflows/custom-create-endpoint.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: mlops/azureml/deploy/online/online-endpoint.yml
        endpoint_name: teleco-churn-endpoint
        endpoint_type: online
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}

  # 8. Create Deployment (Local)
  create-deployment:
      uses: ./.github/workflows/custom-create-deployment.yml
      needs: [get-config,register-environment-deploy,create-endpoint]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: mlops/azureml/deploy/online/online-deployment.yml
        endpoint_name: teleco-churn-endpoint
        endpoint_type: online
        deployment_name: teleco-churn-online-dp
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}

  # 9. Allocate Traffic (Local)
  allocate-traffic:
      uses: ./.github/workflows/custom-allocate-traffic.yml
      needs: [get-config,create-deployment]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        traffic_allocation: teleco-churn-online-dp=100
        endpoint_name: teleco-churn-endpoint
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
